title: RK blog on nothing...:) 
author: Radhakrishna Naik
email: radhakrishna.naik@gmail.copm
description: > # this means to ignore newlines until "baseurl:"
 There is nothing to blog about, its just an example.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
